diff -dur clxclient-3.9.0.orig/Makefile clxclient-3.9.0/Makefile
--- clxclient-3.9.0.orig/Makefile	2013-06-28 16:50:51.000000000 +0200
+++ clxclient-3.9.0/Makefile	2016-10-15 12:44:49.260424973 +0200
@@ -31,7 +31,7 @@
 VERSION = $(MAJVERS).$(MINVERS)
 
 
-CPPFLAGS += -Wall -I. -I/usr/X11R6/include `freetype-config --cflags` -fpic -DVERSION=\"$(VERSION)\" -D_REENTRANT -D_POSIX_PTHREAD_SEMANTICS -O2 
+CPPFLAGS += -Wall -I. -I/usr/X11R6/include `freetype-config --cflags` -fpic -DVERSION=\"$(VERSION)\" -D_REENTRANT -D_POSIX_PTHREAD_SEMANTICS
 LDFLAGS += -L/usr/X11R6/$(LIBDIR) `freetype-config --libs`
 LDLIBS +=
 
@@ -39,21 +39,21 @@
 CLXCLIENT_SO = libclxclient.so
 CLXCLIENT_MAJ = $(CLXCLIENT_SO).$(MAJVERS)
 CLXCLIENT_MIN = $(CLXCLIENT_MAJ).$(MINVERS)
-CLXCLIENT_DEP = -lpthread -lXft -lX11
+CLXCLIENT_DEP = -lclthreads -lXft -lX11 -lpthread
 CLXCLIENT_O = xdisplay.o xresman.o xhandler.o xwindow.o xdraw.o \
 	button.o textip.o enumip.o menuwin.o scale.o slider.o scroll.o mclist.o meter.o
 CLXCLIENT_H = clxclient.h
 
 
 $(CLXCLIENT_MIN): $(CLXCLIENT_O)
-	g++ -shared $(LDFLAGS) -Wl,-soname,$(CLXCLIENT_MAJ) -o $(CLXCLIENT_MIN) $(CLXCLIENT_O) $(CLXCLIENT_DEP)
+	$(CXX) -shared $(LDFLAGS) -Wl,-soname,$(CLXCLIENT_MAJ) -o $(CLXCLIENT_MIN) $(CLXCLIENT_O) $(CLXCLIENT_DEP)
 
 
 install:	$(CLXCLIENT_MIN)
 	install -d $(PREFIX)/$(LIBDIR)
 	install -m 644 $(CLXCLIENT_H) $(PREFIX)/include
 	install -m 755 $(CLXCLIENT_MIN) $(PREFIX)/$(LIBDIR)
-	ldconfig
+	/sbin/ldconfig -n -N $(PREFIX)/$(LIBDIR)
 	ln -sf $(CLXCLIENT_MIN) $(PREFIX)/$(LIBDIR)/$(CLXCLIENT_SO)
 
 
