--- clxclient-3.9.2/source/Makefile.orig	2018-08-24 20:50:31.000000000 +0200
+++ clxclient-3.9.2/source/Makefile	2021-09-27 19:15:58.074346409 +0200
@@ -30,17 +30,16 @@ MINVERS = 9.2
 VERSION = $(MAJVERS).$(MINVERS)
 
 
-CPPFLAGS += $(shell pkgconf --cflags freetype2) 
+CPPFLAGS += -I. $(shell pkg-config --cflags xft)
 CPPFLAGS += -DVERSION=\"$(VERSION)\" -D_REENTRANT -D_POSIX_PTHREAD_SEMANTICS $(PCONFCFL)
-CXXFLAGS += -Wall -O2 -fPIC 
-CXXFLAGS += -march=native
+CXXFLAGS += -Wall -fPIC
 LDLIBS +=
 
 
 CLXCLIENT_SO = libclxclient.so
 CLXCLIENT_MAJ = $(CLXCLIENT_SO).$(MAJVERS)
 CLXCLIENT_MIN = $(CLXCLIENT_MAJ).$(MINVERS)
-CLXCLIENT_DEP = -lpthread -lXft -lX11
+CLXCLIENT_DEP = -lclthreads -lXft -lX11 -lpthread
 CLXCLIENT_O = xdisplay.o xresman.o xhandler.o xwindow.o xdraw.o \
 	button.o textip.o enumip.o menuwin.o scale.o slider.o scroll.o mclist.o meter.o
 CLXCLIENT_H = clxclient.h
@@ -55,7 +54,7 @@ install:	$(CLXCLIENT_MIN)
 	install -d $(DESTDIR)$(LIBDIR)
 	install -m 644 $(CLXCLIENT_H) $(DESTDIR)$(INCDIR)
 	install -m 755 $(CLXCLIENT_MIN) $(DESTDIR)$(LIBDIR)
-	ldconfig
+	-/sbin/ldconfig -n -N $(DESTDIR)$(LIBDIR)
 	ln -sf $(CLXCLIENT_MIN) $(DESTDIR)$(LIBDIR)/$(CLXCLIENT_SO)
 
 uninstall:
